language: java
dist: trusty
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - smitalejandro96@gmail.com
    on_failure: always
